/*
 * Laica PS7002 / YoHealth BLE research logger
 *
 * Purpose
 * -------
 * Passively receive YoHealth BLE advertising frames from a Laica PS7002 or
 * compatible scale, decode the final measurement and reproduce the complete
 * eight-field body-composition result generated by the historical YoHealth
 * getHealth() routine.
 *
 * The formulas and field mapping were recovered from historical native-code
 * artifacts and from the decompiled Android application that consumed the
 * getHealth() output. The PS7002 is the directly validated reference device.
 *
 * This is interoperability/research software, not a medical device.
 *
 * License: MIT - see repository LICENSE.
 */

#include <Arduino.h>
#include <NimBLEDevice.h>
#include <math.h>
#include <string.h>
#include <string>

// -----------------------------------------------------------------------------
// User profile
// -----------------------------------------------------------------------------
// These values MUST match the profile configured in the companion application
// when validating the recovered algorithm.
//
// Current reference profile:
//   male, age 55, height 175 cm.
//
// Age is an explicit algorithm input. Update it after a birthday if the app
// profile also changes age.

static constexpr bool    PROFILE_MALE      = true;
static constexpr uint8_t PROFILE_AGE_YEARS = 55;
static constexpr float   PROFILE_HEIGHT_CM = 175.0f;

// -----------------------------------------------------------------------------
// BLE scanner configuration
// -----------------------------------------------------------------------------

static constexpr uint32_t SERIAL_BAUD = 115200;
static constexpr bool ACTIVE_SCAN = false;
static constexpr bool SCAN_DUPLICATES = true;
static constexpr uint32_t SESSION_GAP_MS = 5000;
static constexpr uint32_t SCAN_PERIOD_MS = 30000;

// -----------------------------------------------------------------------------
// YoHealth manufacturer-data layout
// -----------------------------------------------------------------------------
// NimBLE getManufacturerData() includes the two manufacturer/company-ID bytes.
//
//   02 A1 09 FF WW WW ZZ ZZ SS FF FF MM CC AA
//   ----- ----- ----- ----- -- ----- -- -- --
//     |     |     |     |    |   |   |  |  +-- terminator 0xAA
//     |     |     |     |    |   |   |  +----- checksum
//     |     |     |     |    |   |   +-------- mode/precision byte (e.g. 0x21)
//     |     |     |     |    |   +------------ reserved/unknown in captures
//     |     |     |     |    +---------------- status flags
//     |     |     |     +--------------------- health/impedance, big-endian
//     |     |     +--------------------------- raw weight, big-endian
//     |     +--------------------------------- YoHealth header 09 FF
//     +--------------------------------------- manufacturer bytes 02 A1
//
// Historical YoHealth Android code interpreted MM as a two-decimal-digit code
// represented by the hexadecimal byte text. For example 0x21 -> "21":
//
//   tens digit 1 -> weight-only scale
//   tens digit 2 -> body-composition scale
//   ones digit 1 -> raw weight / 10   (0.1 kg resolution)
//   ones digit 2 -> raw weight / 100  (0.01 kg resolution)
//
// PS7002 captures consistently use 0x21.

static constexpr size_t MFG_LEN = 14;

static constexpr uint8_t STATUS_REALTIME_PS7002 = 0x80;
static constexpr uint8_t STATUS_STABLE_NO_BIA   = 0x82;
static constexpr uint8_t STATUS_STABLE_BIA      = 0x86;

// -----------------------------------------------------------------------------
// Decoded protocol/result structures
// -----------------------------------------------------------------------------

struct DeviceModeInfo {
  uint8_t rawByte;
  int code;              // BCD-style decimal code, e.g. 0x21 -> 21
  int deviceType;        // 0 weight-only, 1 body-composition, -1 unknown
  uint8_t precisionDigit;// 1 => /10, 2 => /100, otherwise unknown
  bool highPrecision;
  bool validBcd;
};

struct BodyMetrics {
  float weightKg;
  uint16_t impedance;

  // Internal value used by several formulas; not a user-facing YoHealth field.
  float leanMassKg;

  // Eight YoHealth output fields, expressed in the units used by the app.
  float bmi;
  float bodyFatPct;
  float waterPct;
  float musclePct;
  float boneMassKg;
  float visceralFatPct;
  int   bodyAge;
  int   bmrKcal;
};

// -----------------------------------------------------------------------------
// Session state
// -----------------------------------------------------------------------------

static uint32_t lastYoHealthSeenMs = 0;
static bool sessionActive = false;
static bool finalMeasurementEmitted = false;
static uint32_t measurementCounter = 0;
static uint8_t lastObservedMfg[MFG_LEN];
static bool haveLastObservedMfg = false;

// -----------------------------------------------------------------------------
// Small helpers
// -----------------------------------------------------------------------------

static uint16_t readBE16(const uint8_t *p) {
  return ((uint16_t)p[0] << 8) | p[1];
}

static void printHexByte(uint8_t value) {
  if (value < 0x10) Serial.print('0');
  Serial.print(value, HEX);
}

static void printHex(const uint8_t *data, size_t len) {
  for (size_t i = 0; i < len; ++i) {
    printHexByte(data[i]);
    if (i + 1 < len) Serial.print(' ');
  }
}

static uint8_t protocolChecksum(const uint8_t *data) {
  // Confirmed from PS7002 captures and historical PS7200L examples:
  // checksum = low 8 bits of manufacturer-data bytes 0..11.
  uint16_t sum = 0;
  for (size_t i = 0; i <= 11; ++i) sum += data[i];
  return (uint8_t)(sum & 0xFF);
}

static bool checksumValid(const uint8_t *data) {
  return protocolChecksum(data) == data[12];
}

static bool isYoHealthPacket(const uint8_t *data, size_t len) {
  if (len != MFG_LEN) return false;
  if (data[0] != 0x02 || data[1] != 0xA1) return false;
  if (data[2] != 0x09 || data[3] != 0xFF) return false;
  if (data[13] != 0xAA) return false;
  return true;
}

static DeviceModeInfo decodeDeviceMode(uint8_t raw) {
  DeviceModeInfo info{};
  info.rawByte = raw;

  const uint8_t tens = (raw >> 4) & 0x0F;
  const uint8_t ones = raw & 0x0F;
  info.validBcd = (tens <= 9 && ones <= 9);
  info.code = info.validBcd ? (tens * 10 + ones) : -1;
  info.precisionDigit = info.validBcd ? ones : 0;
  info.highPrecision = (info.precisionDigit == 2);
  info.deviceType = -1;

  // Mirrors the historical YoHealth application logic.
  if (info.code > 10 && info.code < 20) {
    info.deviceType = 0;
  } else if (info.code > 20 && info.code < 30) {
    info.deviceType = 1;
  }

  return info;
}

static float decodeWeightKg(uint16_t rawWeight, const DeviceModeInfo &mode) {
  if (mode.precisionDigit == 2) return rawWeight / 100.0f;
  if (mode.precisionDigit == 1) return rawWeight / 10.0f;

  // Conservative fallback for the directly validated PS7002 behavior.
  return rawWeight / 10.0f;
}

static bool statusIsStable(uint8_t status) {
  // Historical app used bit 1 as the real-time/stable lock flag.
  return (status & 0x02) != 0;
}

static bool statusAllowsBodyComposition(uint8_t status) {
  // In the historical app, a stable frame whose low nibble equals 2 was a
  // stable weight-only/no-electrode condition for a body-composition scale.
  return statusIsStable(status) && ((status & 0x0F) != 0x02);
}

static const char *statusName(uint8_t status) {
  if (status == STATUS_REALTIME_PS7002) return "REALTIME";
  if (status == STATUS_STABLE_NO_BIA)   return "STABLE_WEIGHT_ONLY/NO_BIA";
  if (status == STATUS_STABLE_BIA)      return "STABLE_BODY_COMPOSITION";
  if (statusIsStable(status))           return "STABLE_OTHER";
  return "REALTIME_OTHER";
}

static const char *deviceTypeName(int type) {
  switch (type) {
    case 0:  return "WEIGHT_ONLY";
    case 1:  return "BODY_COMPOSITION";
    default: return "UNKNOWN";
  }
}

// -----------------------------------------------------------------------------
// Recovered YoHealth getHealth() algorithm
// -----------------------------------------------------------------------------
// Historical Android source establishes the native call signature as:
//
//   getHealth(sex, age, height_cm, weight_kg, impedance)
//
// with sex 0=male, 1=female. The native routine returns eight CSV fields:
//
//   0 BMI
//   1 body-fat fraction
//   2 water fraction
//   3 muscle fraction
//   4 bone native value (Android divides it by 30 -> kg)
//   5 visceral-fat fraction
//   6 body age
//   7 BMR
//
// The implementation below computes the user-facing values directly.

static BodyMetrics calculateBodyMetrics(float weightKg, uint16_t impedance) {
  BodyMetrics m{};

  const float age = (float)PROFILE_AGE_YEARS;
  const float h = PROFILE_HEIGHT_CM;
  const float sex = PROFILE_MALE ? 0.0f : 1.0f;
  const float heightM = h / 100.0f;

  m.weightKg = weightKg;
  m.impedance = impedance;
  m.bmi = weightKg / (heightM * heightM);

  // Central lean-mass estimate reconstructed from native getHealth().
  m.leanMassKg =
      0.00067f * h * h
      + 2.0f
      + 0.53f * weightKg
      - 0.00095f * (float)impedance
      - 3.0f * sex
      - 0.05f * age;

  // Body-fat fraction plus the native low-fat correction.
  float fatFraction = (weightKg - m.leanMassKg) / weightKg;
  if (fatFraction < 0.10f) {
    fatFraction = fatFraction + 0.7f * (0.10f - fatFraction);
  }
  m.bodyFatPct = fatFraction * 100.0f;

  // Water fraction = 73% of estimated lean mass, normalized by body weight.
  const float waterFraction = 0.73f * m.leanMassKg / weightKg;
  m.waterPct = waterFraction * 100.0f;

  if (PROFILE_MALE) {
    m.musclePct =
        ((7.78f * h + 334.0f - 9.8f * age) / weightKg) + 24.4f;

    m.bmrKcal = (int)lround(
        13.7 * (double)weightKg
        + 5.0 * (double)h
        - 6.8 * (double)age
        + 66.0);
  } else {
    m.musclePct =
        ((7.74f * h - 318.0f - 9.8f * age) / weightKg) + 24.4f;

    m.bmrKcal = (int)lround(
        9.6 * (double)weightKg
        + 1.8 * (double)h
        - 4.7 * (double)age
        + 655.0);
  }

  // Native field 4 is 30 * this value. Historical Android code divides that
  // field by 30 and passes the result to stableData() as boneMass.
  float boneMass =
      0.0077200001f * weightKg
      + 0.0045f * h
      + 1.95f
      - 0.00636f * age
      - 0.000232f * (float)impedance;

  if (!PROFILE_MALE) {
    boneMass *= 0.75f;
  }
  m.boneMassKg = boneMass;

  // Native field 5 is a sex-dependent multiple of fat fraction. Historical
  // Android code multiplies it by 100 and labels it visceralFatPercentage.
  const float visceralFraction =
      fatFraction * (PROFILE_MALE ? 0.45f : 0.20f);
  m.visceralFatPct = visceralFraction * 100.0f;

  // Body-age heuristic recovered from the final native branch.
  const int ageInt = PROFILE_AGE_YEARS;
  if (ageInt < 20) {
    m.bodyAge = ageInt;
  } else if (m.bmi > 28.0f) {
    m.bodyAge = ageInt + 15;
  } else if (m.bmi > 26.0f) {
    m.bodyAge = ageInt + 12;
  } else if (m.bmi > 25.0f) {
    m.bodyAge = ageInt + 7;
  } else if (m.bmi > 23.0f) {
    m.bodyAge = ageInt + 4;
  } else if (ageInt < 30) {
    m.bodyAge = 18;
  } else if (ageInt <= 44) {
    m.bodyAge = ageInt - 12;
  } else {
    m.bodyAge = ageInt - 16;
  }

  return m;
}

// -----------------------------------------------------------------------------
// Output
// -----------------------------------------------------------------------------

static void printFinalMeasurement(const NimBLEAdvertisedDevice *dev,
                                  const uint8_t *data,
                                  const DeviceModeInfo &mode,
                                  float weightKg,
                                  uint16_t impedance) {
  const BodyMetrics m = calculateBodyMetrics(weightKg, impedance);
  ++measurementCounter;

  Serial.println();
  Serial.println("============================================================");
  Serial.printf("FINAL MEASUREMENT #%lu\n", (unsigned long)measurementCounter);
  Serial.println("============================================================");
  Serial.printf("RSSI                     : %d dBm\n", dev->getRSSI());
  Serial.print ("Manufacturer data        : "); printHex(data, MFG_LEN); Serial.println();
  Serial.printf("Checksum                 : 0x%02X [OK]\n", data[12]);
  Serial.printf("Status                   : 0x%02X (%s)\n", data[8], statusName(data[8]));
  Serial.printf("Device mode              : 0x%02X (code %d, %s)\n",
                mode.rawByte, mode.code, deviceTypeName(mode.deviceType));
  if (mode.precisionDigit == 1) {
    Serial.println("Weight resolution        : 0.1 kg");
  } else if (mode.precisionDigit == 2) {
    Serial.println("Weight resolution        : 0.01 kg");
  } else {
    Serial.println("Weight resolution        : unknown (fallback /10 used)");
  }

  Serial.println();
  Serial.printf("Weight                   : %.2f kg\n", m.weightKg);
  Serial.printf("Impedance / health       : %u\n", m.impedance);
  Serial.printf("BMI                      : %.2f\n", m.bmi);
  Serial.printf("Lean mass (internal)     : %.3f kg\n", m.leanMassKg);
  Serial.printf("Body fat                 : %.2f %%\n", m.bodyFatPct);
  Serial.printf("Water                    : %.2f %%\n", m.waterPct);
  Serial.printf("Muscle                   : %.2f %%\n", m.musclePct);
  Serial.printf("Bone mass (YoHealth)     : %.3f kg\n", m.boneMassKg);
  Serial.printf("Visceral fat (YoHealth)  : %.2f %%\n", m.visceralFatPct);
  Serial.printf("Body age (YoHealth)      : %d years\n", m.bodyAge);
  Serial.printf("BMR                      : %d kcal/day\n", m.bmrKcal);
  Serial.println();
  Serial.println("Note: some current LAICA apps may hide bone mass, visceral fat and body age");
  Serial.println("even though these fields are produced by the historical YoHealth algorithm.");

  Serial.println();
  Serial.println("CSV_HEADER,seq,weight_kg,impedance,bmi,lean_kg,fat_pct,water_pct,muscle_pct,bone_kg,visceral_fat_pct,body_age,bmr_kcal,status,mode_raw,mode_code,device_type,rssi,mfg");
  Serial.print("CSV,");
  Serial.print(measurementCounter); Serial.print(',');
  Serial.print(m.weightKg, 2); Serial.print(',');
  Serial.print(m.impedance); Serial.print(',');
  Serial.print(m.bmi, 4); Serial.print(',');
  Serial.print(m.leanMassKg, 4); Serial.print(',');
  Serial.print(m.bodyFatPct, 4); Serial.print(',');
  Serial.print(m.waterPct, 4); Serial.print(',');
  Serial.print(m.musclePct, 4); Serial.print(',');
  Serial.print(m.boneMassKg, 4); Serial.print(',');
  Serial.print(m.visceralFatPct, 4); Serial.print(',');
  Serial.print(m.bodyAge); Serial.print(',');
  Serial.print(m.bmrKcal); Serial.print(',');
  Serial.printf("%02X,", data[8]);
  Serial.printf("%02X,", mode.rawByte);
  Serial.print(mode.code); Serial.print(',');
  Serial.print(mode.deviceType); Serial.print(',');
  Serial.print(dev->getRSSI()); Serial.print(',');
  for (size_t i = 0; i < MFG_LEN; ++i) printHexByte(data[i]);
  Serial.println();
  Serial.println("============================================================");
}

// -----------------------------------------------------------------------------
// Packet processing
// -----------------------------------------------------------------------------

static void processYoHealth(const NimBLEAdvertisedDevice *dev,
                            const uint8_t *data) {
  const uint32_t now = millis();

  if (!sessionActive || (uint32_t)(now - lastYoHealthSeenMs) > SESSION_GAP_MS) {
    sessionActive = true;
    finalMeasurementEmitted = false;
    haveLastObservedMfg = false;
    Serial.println();
    Serial.println("[YoHealth] New measurement session detected");
  }
  lastYoHealthSeenMs = now;

  if (!checksumValid(data)) {
    Serial.printf("[YoHealth] Ignored packet: checksum fail (rx=%02X calc=%02X)\n",
                  data[12], protocolChecksum(data));
    return;
  }

  const uint16_t weightRaw = readBE16(data + 4);
  const uint16_t healthRaw = readBE16(data + 6);
  const uint8_t status = data[8];
  const DeviceModeInfo mode = decodeDeviceMode(data[11]);
  const float weightKg = decodeWeightKg(weightRaw, mode);

  const bool payloadChanged =
      !haveLastObservedMfg || memcmp(lastObservedMfg, data, MFG_LEN) != 0;

  if (payloadChanged) {
    memcpy(lastObservedMfg, data, MFG_LEN);
    haveLastObservedMfg = true;

    Serial.printf("[YoHealth] weight=%.2f kg health=", weightKg);
    if (healthRaw == 0xFFFF) Serial.print("NA");
    else Serial.print(healthRaw);
    Serial.printf(" status=0x%02X %s mode=0x%02X/%d\n",
                  status, statusName(status), mode.rawByte, mode.code);
  }

  const bool healthValid = (healthRaw != 0xFFFF && healthRaw != 0x0000);

  // This mirrors the historical app more closely than hard-coding only 0x86:
  // stable bit set, not the low-nibble 0x2 no-BIA condition, and valid health.
  // On the PS7002 this resolves to the observed 0x86 final frame.
  const bool finalFrame = healthValid && statusAllowsBodyComposition(status);

  if (finalFrame && !finalMeasurementEmitted) {
    finalMeasurementEmitted = true;
    printFinalMeasurement(dev, data, mode, weightKg, healthRaw);
  }
}

// -----------------------------------------------------------------------------
// NimBLE callbacks
// -----------------------------------------------------------------------------

class ScaleScanCallbacks : public NimBLEScanCallbacks {
 public:
  void inspect(const NimBLEAdvertisedDevice *dev) {
    if (!dev->haveManufacturerData()) return;

    const std::string mfg = dev->getManufacturerData();
    if (mfg.size() != MFG_LEN) return;

    const uint8_t *data = reinterpret_cast<const uint8_t *>(mfg.data());
    if (!isYoHealthPacket(data, mfg.size())) return;

    processYoHealth(dev, data);
  }

  void onDiscovered(const NimBLEAdvertisedDevice *dev) override {
    inspect(dev);
  }

  void onResult(const NimBLEAdvertisedDevice *dev) override {
    inspect(dev);
  }

  void onScanEnd(const NimBLEScanResults &results, int reason) override {
    Serial.printf("[BLE] Scan ended (reason=%d), restarting\n", reason);
    NimBLEDevice::getScan()->start(SCAN_PERIOD_MS, false, true);
  }
};

static ScaleScanCallbacks scanCallbacks;

// -----------------------------------------------------------------------------
// Arduino entry points
// -----------------------------------------------------------------------------

void setup() {
  Serial.begin(SERIAL_BAUD);
  delay(800);

  Serial.println();
  Serial.println("LAICA / YoHealth BLE body-composition research logger");
  Serial.println("Reference device: LAICA PS7002 Smart");
  Serial.println("MIT licensed research implementation");
  Serial.println();
  Serial.printf("Profile: %s, age=%u, height=%.1f cm\n",
                PROFILE_MALE ? "male" : "female",
                PROFILE_AGE_YEARS,
                PROFILE_HEIGHT_CM);
  Serial.println("Waiting for a stable YoHealth frame with valid impedance...");

  NimBLEDevice::init("");
  NimBLEScan *scan = NimBLEDevice::getScan();
  scan->setScanCallbacks(&scanCallbacks, SCAN_DUPLICATES);
  scan->setActiveScan(ACTIVE_SCAN);
  scan->setMaxResults(0);
  scan->start(SCAN_PERIOD_MS, false, true);
}

void loop() {
  if (sessionActive &&
      (uint32_t)(millis() - lastYoHealthSeenMs) > SESSION_GAP_MS) {
    sessionActive = false;
    finalMeasurementEmitted = false;
    Serial.println("[YoHealth] Session closed; ready for next weighing");
  }

  delay(100);
}
